Create form views - MP-36, MP-37, MP-38, MP-39 (feature/mp-36-39)
MFG-POS/mfg-pos pull request #12
Opened 2021-05-16 15:37 UTC by dominikmlynarczyk

**Below is a description of the changes:**

**1. Changes to the model**
Based on our discussions, I have applied changes to the model, especially the ingredient model. In the documentation we considered storing a picture (`imagePath`), but it doesn't make much sense to keep a picture for an ingredient (the end user won't be taking a picture of let's say "sugar", come on...). 
In the case of ingredients, if you think that it is worth to leave it, I suggest leaving it as an optional field, and providing placeholder image.

Similarly for ingredient categories - this is included in the documentation, but it doesn't make much sense in my opinion. Maybe when the application will expand and we will have a warehouse this need will appear, but I would let it go for now. If anyone thinks that it should stay, please provide reasoning - remember that you have to define a separate endpoint for ingredient categories, because these categories are not displayed in the terminal.

As we discussed, I added an optional `tax` type for the Category that will define a fixed tax value for the category and this value should be able to be inherited by all products/dishes in the category.

I applied some other changes to model - especially look for a change in imagePath to image, because `<input>` with the `file` type returns a `FileList` object and this will be needed when retrieving data from the form.

**2. Problems**
I had a problem with typing `name` and `register` fields, when creating an abstraction for form fields. I used the type `any` and this should be fixed - please give me a suggestion on this issue.

I don't really know how to solve the issue of calculating the price for a dish. The documentation here contains a lot of inconsistent information, because there we still consider the weight of net and gross products. What do we want to do with this, given that the warehouse is not ready?

**3. Known issues**
The Select element gets a placeholder value when the parent component is re-rendered - the correct value is sent, but this is strictly a UI issue. 

Calculating pricing for article & dish is not working - consider it for MP-36 to MP-39 tickets to be only a mock view.

2021-05-16 19:01 UTC, mfurmanit requested changes
Well done! 👍 
I have couple things to resolve / fix / discuss.

2021-05-16 19:01 UTC, mfurmanit commented on src/components/atoms/FileUploadIcon/index.tsx
> +    boxSize={12}
That's the thing which I wanted to discuss. 
Should we use braces (`{}`) or quote marks (`""`) when defining single values for styles properties?
(in `boxSize` you use braces, in the others quotes)
I suggest using quotes for single values and of course braces for more robust styling (responsiveness).

2021-05-16 19:01 UTC, mfurmanit commented on src/model/documents/category.ts
> +  tax?: string[];
That should be probably typed as `Tax`, not array of string (??).

2021-05-16 19:01 UTC, mfurmanit commented on src/others/input-types.ts
> +export type InputTypes =
That should be `InputType` without ending `s`.
We don't write `CategorieS` or `TaxeS`.
It's not array, it's a type.

2021-05-16 19:01 UTC, mfurmanit commented on src/routing.tsx
> +import Categories from 'components/Tables/Categories'; // To be changed later for proper view - views/Menu/Categories
Write it as `// TODO` please - this way IDE will be able to investigate such things easily in the future.

2021-05-16 19:01 UTC, mfurmanit commented on src/views/Menu/DishForm.tsx
> +          validation={{ required: 'To pole jest wymagane' }}
You can add default validation messages to components starting with `FormGroup` - here you use same message for every required field.

2021-05-16 19:01 UTC, mfurmanit commented on src/components/Table/Toolbar.tsx
> +      <Button as={RouterLink} to={ROUTE_MENU_FORMS.CATEGORY.path} size="md" onClick={props.onButtonClick}>
It should be passed in props, because it is generic component that will be used in many tables.

2021-05-16 19:01 UTC, mfurmanit commented on src/components/molecules/FormGroupFileUpload/index.tsx
> +  name: FieldPath<any>;
As we discussed on Teams.
You need to make `props` and component generic by passing `<T>` which will evaluate to types like `Category`, `Product` and so on.

2021-05-16 19:04 UTC, kacpergadula approved these changes

2021-05-22 10:43 UTC, dominikmlynarczyk commented on src/components/atoms/FileUploadIcon/index.tsx
> +    boxSize={12}
Thank you for pointing this out. I changed the value passing from `{}` notation to single quote notation. It is worth noting, that there are exceptions where Chakra requires props to be passed using `{}` (e.g. in `FormGroupFileUpload` the `borderWidth` prop).

2021-05-22 10:44 UTC, dominikmlynarczyk commented on src/others/input-types.ts
> +export type InputTypes =
Indeed, sorry. Already fixed 🩹.

2021-05-22 10:46 UTC, dominikmlynarczyk commented on src/model/documents/category.ts
> +  tax?: string[];
I applied some changes and caught brain lag probably. Good for us that you noticed that.
Fixed.

2021-05-22 10:47 UTC, dominikmlynarczyk commented on src/routing.tsx
> +import Categories from 'components/Tables/Categories'; // To be changed later for proper view - views/Menu/Categories
Added "TODO: " for future code clean up.

2021-05-22 12:54 UTC, dominikmlynarczyk commented on src/components/Table/Toolbar.tsx
> +      <Button as={RouterLink} to={ROUTE_MENU_FORMS.CATEGORY.path} size="md" onClick={props.onButtonClick}>
Extracted error message to const.

2021-05-22 12:54 UTC, dominikmlynarczyk commented on src/views/Menu/DishForm.tsx
> +          validation={{ required: 'To pole jest wymagane' }}
Extracted error message to const.

2021-05-25 17:44 UTC, dominikmlynarczyk commented on src/components/Table/Toolbar.tsx
> +      <Button as={RouterLink} to={ROUTE_MENU_FORMS.CATEGORY.path} size="md" onClick={props.onButtonClick}>
We resolved this issue and agreed that this change would be in Maciej's PR.

2021-05-25 17:46 UTC, dominikmlynarczyk commented on src/components/molecules/FormGroupFileUpload/index.tsx
> +  name: FieldPath<any>;
We have temporarily solved this issue by replacing interfaces with types. This has its limitations, one of the biggest current bugs is having to remove the parent property from the Category type due to the "circularly referenced type in TypeScript" error

2021-05-25 18:03 UTC, mfurmanit commented on src/components/Table/Toolbar.tsx
> +      <Button as={RouterLink} to={ROUTE_MENU_FORMS.CATEGORY.path} size="md" onClick={props.onButtonClick}>
Yup, it is already there. 👍

2021-05-25 18:08 UTC, mfurmanit approved these changes

2021-05-25 18:08 UTC, merged